### ISSUE TITLE
Configurar base de datos SQL

### ISSUE THREAD

**Issue by ayubero** [UNIZAR-30226-2024-12/backend#1]
Acceder a Hetzner, instalar PostgreSQL y compartir claves con el equipo.

**Comment by akarafy** [comment]
Accedido a Hetzner configurado usuario "wealth".
Instalado potgresql creado en postgre un superusuario de nombre super con todos los privilegios, creado otro usuario llamado backend_escritura con solo permisos de escritura, lectura, borrado y creación de triggers.
Creada estrucutra de la base de datos.
